Repository djolewalker/UksHub, pull requests merged in 2022-02, with the labels that each got.

#77 [62-permissions] Permissions are implemented
  UksHub/apps/hub/services.py
  UksHub/apps/hub/templatetags/hub_filters.py
  UksHub/apps/hub/views/repository.py
  UksHub/templates/hub/common/artefact.html
  UksHub/templates/hub/common/comment.html
  UksHub/templates/hub/profile/stars.html
  UksHub/templates/hub/repository/base.html
  UksHub/templates/hub/repository/issue.html
  UksHub/templates/hub/repository/pull-request.html
Labels: enhancement, auth

#78 Feature 25 repository settings
  UksHub/apps/gitcore/forms.py
  UksHub/apps/gitcore/models.py
  UksHub/apps/gitcore/urls.py
  UksHub/apps/hub/services.py
  UksHub/apps/hub/urls.py
  UksHub/apps/hub/views/profile.py
  UksHub/apps/hub/views/repository.py
  UksHub/templates/hub/repository/base.html
  UksHub/templates/hub/repository/repository-settings.html
  UksHub/templates/hub/repository/settings/collaborators.html
  UksHub/templates/hub/repository/settings/repo-main-settings.html
  UksHub/templates/hub/user-settings/settings-profile.html
Labels: enhancement

#79 Feature 23 user home dashboard
  UksHub/apps/gitcore/models.py
  UksHub/apps/hub/urls.py
  UksHub/apps/hub/views/home.py
  UksHub/static/styles/hub/home-hub.scss
  UksHub/templates/hub/home-hub/home-hub.html
  UksHub/templates/hub/home-hub/repo-cards.html
  UksHub/templates/hub/home-hub/sidebar.html
  UksHub/templates/hub/hub-base.html
Labels: enhancement

#81 Bugfix 80 list starred repos
  UksHub/apps/hub/views/profile.py
  UksHub/templates/hub/profile/stars.html
Labels: bug, enhancement

#82 [35-insights] Insights implemented
  UksHub/apps/advancedsearch/mapper.py
  UksHub/apps/hub/urls.py
  UksHub/apps/hub/views/repository.py
  UksHub/templates/hub/common/artefact-inline.html
  UksHub/templates/hub/common/profile-picture.html
  UksHub/templates/hub/repository/base.html
  UksHub/templates/hub/repository/insights.html
  UksHub/templates/hub/repository/insights/commits.html
  UksHub/templates/hub/repository/insights/pulse.html
  UksHub/templates/hub/repository/insights/traffic.html
  UksHub/templates/hub/repository/repository-settings.html
Labels: enhancement

#85 [84-analytics] Fixes in graphs
  UksHub/apps/gitcore/services.py
  UksHub/apps/hub/views/repository.py
  UksHub/settings/dev.py
  UksHub/templates/hub/repository/base.html
Labels: bug

#87 Feature 52 create milestones section
  UksHub/apps/events/services.py
  UksHub/apps/hub/forms.py
  UksHub/apps/hub/models.py
  UksHub/apps/hub/templatetags/hub_filters.py
  UksHub/apps/hub/urls.py
  UksHub/apps/hub/views/repository.py
  UksHub/static/styles/base.scss
  UksHub/static/styles/hub/hub-base.scss
  UksHub/templates/hub/common/artefact.html
  UksHub/templates/hub/common/event.html
  UksHub/templates/hub/common/new-artefact.html
  UksHub/templates/hub/milestones/create-milestone.html
  UksHub/templates/hub/milestones/milestone-filter-bar.html
  UksHub/templates/hub/milestones/milestone-inline.html
  UksHub/templates/hub/milestones/milestone.html
  UksHub/templates/hub/milestones/milestones.html
  UksHub/templates/hub/repository/artefacts.html
Labels: enhancement

#90 many small styling chages
  UksHub/static/img/hub-icon.svg
  UksHub/templates/auth/login.html
  UksHub/templates/hub/home.html
  UksHub/templates/hub/hub-base.html
  UksHub/templates/hub/profile/repositories.html
  UksHub/templates/hub/profile/stars.html
Labels: enhancement

#91 Bugfix final fixes
  UksHub/apps/gitcore/views.py
  UksHub/static/img/hub-logo-vert.svg
  UksHub/templates/hub/repository/insights/commits.html
  scripts/gitolite-entrypoint.sh
Labels: bug
